
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Dec 25 14:25:57 CET 2023
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LTE = 25;
  public static final int CHAR = 44;
  public static final int CONST = 12;
  public static final int NAMESPACE = 3;
  public static final int LPAREN = 37;
  public static final int SEMI = 32;
  public static final int CONTINUE = 7;
  public static final int FOR = 8;
  public static final int MINUS = 16;
  public static final int RPAREN = 38;
  public static final int STATIC = 11;
  public static final int AND = 26;
  public static final int LT = 24;
  public static final int OR = 27;
  public static final int COMMA = 34;
  public static final int INC = 28;
  public static final int DIV = 18;
  public static final int PLUS = 15;
  public static final int ASSIGN = 33;
  public static final int IF = 4;
  public static final int DOT = 31;
  public static final int BOOLEAN = 45;
  public static final int EOF = 0;
  public static final int RETURN = 14;
  public static final int NEW = 41;
  public static final int error = 1;
  public static final int MUL = 17;
  public static final int NUMBER = 43;
  public static final int MOD = 19;
  public static final int NEQ = 21;
  public static final int IDENT = 42;
  public static final int BREAK = 6;
  public static final int VOID = 13;
  public static final int EQ = 20;
  public static final int GTE = 23;
  public static final int COLON = 30;
  public static final int LBRACE = 39;
  public static final int ELSE = 5;
  public static final int LSQUARE = 35;
  public static final int READ = 10;
  public static final int RSQUARE = 36;
  public static final int RBRACE = 40;
  public static final int PROG = 2;
  public static final int DEC = 29;
  public static final int GT = 22;
  public static final int PRINT = 9;
}

